[package]
name = "combine_yara"
version = "3.0.0"
edition = "2021"

[dependencies]
walkdir = "2" #Or newer
colored = "2" #Or newer
common_config = { path = "../common_config" }
common_ui = { path = "../common_ui" }
chrono = "0.4.41"
clap = { version = "4", features = ["derive"] }
