site_name: MalChela Documentation
repo_url: https://github.com/dwmetz/MalChela
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: cyan
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy
extra_css:
  - stylesheets/colors.css
nav:
  - Home: index.md
  - About: about.md  # Suggest separating from Home
  - Installation: install.md
  - Configuration:
      - tools.yaml: configuration/tools-yaml.md
      - api configuration: configuration/api-configuration.md
  - Core Tools:
      - Overview: coretools/index.md
      - Usage: coretools/usage.md
      - MismatchMiner: coretools/mismatchminer.md
      - FileAnalyzer: coretools/fileanalyzer.md
      - MStrings: coretools/mstrings.md
      - MalHash: coretools/malhash.md
      - StringsToYARA: coretools/strings_to_yara.md
      - CombineYARA: coretools/combine_yara.md
      - ExtractSamples: coretools/extract_samples.md
      - HashIt: coretools/hashit.md
      - MZMD5: coretools/mzmd5.md
      - XMZMD5: coretools/xmzmd5.md
      - MZCount: coretools/mzcount.md
      - NSRLQuery: coretools/nsrlquery.md
  - Third-Party Tools:
    - Configuration Reference: tools/tools-yaml.md
    - Enhanced Integrations: tools/enhanced.md
    - TShark: tools/tshark.md
    - FLOSS: tools/floss.md
    - YARA-X: tools/yara-x.md
    - Volatility 3: tools/vol3.md
  - REMnux Mode: remnux.md
  - Support: support.md