site_name: MalChela Documentation
repo_url: https://github.com/dwmetz/MalChela
theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: cyan
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy
plugins:
  - search
  - with-pdf:
      output_path: "pdf/user-guide.pdf"
      exclude_pages:
        - home.md
      
extra_css:
  - stylesheets/colors.css
nav:
  - Home: index.md
  - About: about.md
  - Installation: install.md
  - Configuration:
      - tools.yaml: configuration/tools-yaml.md
      - api configuration: configuration/api-configuration.md
  - Case Management: cases.md
  - Core Tools:
      - Overview: coretools/index.md
      - Usage: coretools/usage.md
      - CombineYARA: coretools/combine_yara.md
      - ExtractSamples: coretools/extract_samples.md
      - FileAnalyzer: coretools/fileanalyzer.md
      - FileMiner: coretools/fileminer.md
      - HashCheck: coretools/hashcheck.md
      - HashIt: coretools/hashit.md
      - MalHash: coretools/malhash.md
      - MStrings: coretools/mstrings.md
      - MZCount: coretools/mzcount.md      
      - MZHash: coretools/mzhash.md
      - NSRLQuery: coretools/nsrlquery.md
      - StringsToYARA: coretools/strings_to_yara.md
      - XMZHash: coretools/xmzhash.md


  - Third-Party Tools:
    - Integrating Third Party Tools: tools/index.md
    - Configuration Reference: tools/tools-yaml.md
    - Enhanced Integrations: tools/enhanced.md
    - TShark: tools/tshark.md
    - PCAP to CSV: tools/pcap_to_csv.md
    - Volatility 3: tools/vol3.md
    - YARA-X: tools/yara-x.md
    - Python Integrations: tools/python.md
  - REMnux Mode: remnux.md
  - Support: support.md